/**
 * Technical Terms Glossary
 * Definitions for tooltips throughout the application
 */

export interface GlossaryTerm {
  term: string;
  definition: string;
  category?: 'metric' | 'technology' | 'stakeholder' | 'concept';
}

export const glossary: Record<string, GlossaryTerm> = {
  // Metrics
  'renewable_share': {
    term: 'Renewable Share',
    definition: 'Percentage of electricity generation from renewable energy sources (solar, wind, hydro, etc.)',
    category: 'metric'
  },
  'installed_capacity': {
    term: 'Installed Capacity',
    definition: 'Total power generation capacity available, measured in megawatts (MW) or gigawatts (GW)',
    category: 'metric'
  },
  'generation': {
    term: 'Electricity Generation',
    definition: 'Amount of electricity produced over a period, measured in gigawatt-hours (GWh) or terawatt-hours (TWh)',
    category: 'metric'
  },
  'emissions': {
    term: 'CO₂ Emissions',
    definition: 'Carbon dioxide released from electricity generation, primarily from fossil fuel combustion',
    category: 'metric'
  },
  'emissions_reduction': {
    term: 'Emissions Reduction',
    definition: 'Percentage decrease in CO₂ emissions compared to a baseline scenario',
    category: 'metric'
  },
  'investment': {
    term: 'Investment',
    definition: 'Capital expenditure required for building new power generation infrastructure',
    category: 'metric'
  },
  'jobs': {
    term: 'Jobs Created',
    definition: 'Employment generated from construction and operation of energy facilities (illustrative estimate)',
    category: 'metric'
  },
  'land_use': {
    term: 'Land Use',
    definition: 'Area required for energy infrastructure, primarily solar and wind farms (illustrative estimate)',
    category: 'metric'
  },
  'peak_demand': {
    term: 'Peak Demand',
    definition: 'Maximum electricity demand that occurs during the highest usage period',
    category: 'metric'
  },

  // Technologies
  'solar_pv': {
    term: 'Solar PV',
    definition: 'Solar photovoltaic panels that convert sunlight directly into electricity',
    category: 'technology'
  },
  'wind': {
    term: 'Wind Power',
    definition: 'Electricity generated by wind turbines (onshore and offshore)',
    category: 'technology'
  },
  'hydro': {
    term: 'Hydropower',
    definition: 'Electricity generated from flowing or falling water',
    category: 'technology'
  },
  'battery': {
    term: 'Battery Storage',
    definition: 'Energy storage systems that store electricity for later use, helping to balance supply and demand',
    category: 'technology'
  },
  'coal': {
    term: 'Coal Power',
    definition: 'Electricity generated by burning coal (fossil fuel)',
    category: 'technology'
  },
  'gas': {
    term: 'Natural Gas',
    definition: 'Electricity generated by burning natural gas (fossil fuel)',
    category: 'technology'
  },
  'biomass': {
    term: 'Biomass',
    definition: 'Electricity generated from organic materials like wood, crops, or waste',
    category: 'technology'
  },
  'geothermal': {
    term: 'Geothermal',
    definition: 'Electricity generated from heat within the Earth',
    category: 'technology'
  },

  // Stakeholder Priorities
  'policy_coherence': {
    term: 'Policy Coherence',
    definition: 'Alignment of energy plans with national climate commitments, industrial policy, and development goals',
    category: 'stakeholder'
  },
  'grid_stability': {
    term: 'Grid Stability',
    definition: 'Ability of the electrical grid to maintain steady voltage and frequency despite changes in supply or demand',
    category: 'stakeholder'
  },
  'system_adequacy': {
    term: 'System Adequacy',
    definition: 'Having sufficient power generation capacity to meet demand at all times',
    category: 'stakeholder'
  },
  'competitiveness': {
    term: 'Industrial Competitiveness',
    definition: 'Ability of industries to compete globally while managing energy costs and reliability',
    category: 'stakeholder'
  },
  'affordability': {
    term: 'Affordability',
    definition: 'Keeping electricity prices accessible for households and businesses',
    category: 'stakeholder'
  },
  'climate_ambition': {
    term: 'Climate Ambition',
    definition: 'Level of effort to reduce greenhouse gas emissions in line with Paris Agreement goals',
    category: 'stakeholder'
  },
  'just_transition': {
    term: 'Just Transition',
    definition: 'Ensuring the shift to clean energy is fair and inclusive, supporting affected workers and communities',
    category: 'stakeholder'
  },
  'evidence_based': {
    term: 'Evidence-Based',
    definition: 'Decisions and policies grounded in rigorous data analysis and scientific research',
    category: 'stakeholder'
  },
  'bankability': {
    term: 'Bankability',
    definition: 'Whether energy projects have low enough risk to attract financing from banks and investors',
    category: 'stakeholder'
  },
  'regional_integration': {
    term: 'Regional Integration',
    definition: 'Cross-border electricity trade and coordinated planning between neighboring countries',
    category: 'stakeholder'
  },
  'debt_sustainability': {
    term: 'Debt Sustainability',
    definition: "Whether a country can finance energy investments without compromising its ability to repay debt",
    category: 'stakeholder'
  },

  // Concepts
  'vre_integration': {
    term: 'VRE Integration',
    definition: 'Variable Renewable Energy integration - managing solar and wind power that varies with weather conditions',
    category: 'concept'
  },
  'capacity_factor': {
    term: 'Capacity Factor',
    definition: 'Percentage of time a power plant operates at full capacity (solar and wind have lower capacity factors)',
    category: 'concept'
  },
  'baseload': {
    term: 'Baseload Power',
    definition: 'Minimum level of electricity demand that must be met 24/7',
    category: 'concept'
  },
  'dispatchable': {
    term: 'Dispatchable Generation',
    definition: 'Power sources that can be turned on/off on demand (e.g., gas, hydro with storage)',
    category: 'concept'
  },
  'intermittency': {
    term: 'Intermittency',
    definition: 'Variability in renewable energy output due to weather (sun, wind) changing throughout the day',
    category: 'concept'
  },
  'stranded_assets': {
    term: 'Stranded Assets',
    definition: 'Existing fossil fuel infrastructure that may become obsolete before end of its useful life',
    category: 'concept'
  },
  'electrification': {
    term: 'Electrification',
    definition: 'Replacing fossil fuels with electricity in transport, heating, and industry',
    category: 'concept'
  },
  'paris_alignment': {
    term: 'Paris Alignment',
    definition: 'Consistency with the Paris Agreement goal to limit global warming to 1.5-2°C',
    category: 'concept'
  },
  'milestone': {
    term: 'Milestone Year',
    definition: 'Key future year for which scenario projections are calculated (e.g., 2030, 2040, 2050)',
    category: 'concept'
  },
  'scenario': {
    term: 'Energy Scenario',
    definition: 'Projected future pathway for energy system development based on specific assumptions and policies',
    category: 'concept'
  }
};

/**
 * Get tooltip definition for a term
 */
export function getTooltip(termKey: string): string | undefined {
  return glossary[termKey]?.definition;
}

/**
 * Get all terms in a category
 */
export function getTermsByCategory(category: GlossaryTerm['category']): GlossaryTerm[] {
  return Object.values(glossary).filter(term => term.category === category);
}
